name: habit_tracker
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  confetti: ^0.7.0
  fl_chart: ^0.66.0
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  intl: ^0.19.0
  fluttertoast: ^9.0.0
  app_usage: ^4.0.1
  audioplayers: ^6.5.1
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  cloud_firestore: ^5.0.0
  google_sign_in: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21

flutter_native_splash:
  color: "#1a1a1a"
  image: assets/images/logo.png
  android_12:
    image: assets/images/logo.png
    color: "#1a1a1a"

flutter:
  uses-material-design: true
  assets:
    - assets/sounds/
    - assets/images/
